version: "3.7"

services:
  postgresx:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=websocket_db
    networks:
      - intranet

networks:
  intranet:
