# Utilizando uma imagem base oficial do Python
FROM python:3.9-slim

# Definindo o diretório de trabalho
WORKDIR /app

# Copiando os arquivos de requisitos
COPY requirements.txt .

# Instalando as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiando o código da aplicação
COPY . .

# Expondo a porta 8000 para o WebSocket
EXPOSE 8000

# Comando para rodar a aplicação
CMD ["python", "server.py"]
